services:
  dashboard:
    build:
      context: app/streamlit
    volumes:
      - ./streamlit:/app
    ports:
      - "8501:8501"
    env_file:
      - .env
    environment:
      DB_HOST: ${POSTGRES_HOST}
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_PORT: ${POSTGRES_PORT}
